#made for side.lv network by Zurius

logout-command:
  enabled: false
  time: 30
  broadcast-times:
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "10"
    - "15"
    - "20"
    - "25"

logger:
  time-till-disappear: 30
  while-in-combat: false
  dont-lose-xp:
    enabled: true
    permission: "no.xp.lose"
  worlds:
    enabled: true
    list:
      - "underground"

messages:
  logger-name: "&4(Logger) &f%player%"
  unknown-command: "&8» &7Unknown command. Type \"&f/help&7\" for help."
  no-permission: "&cYou do not have permissions to use this command!"
  death-message: "&f(Logger) %player% &fwas slain by &f%killer%"
  death-message-null: "&f(Logger) %player% &fdied"
  must-be-player: "&4[!] &cOnly players can execute this command."
  remaining-time: "&7You will be logged out in"
  kick-message: "&f&lSuccessfully logged out."
  title-logout-canceled: "&4Logout Canceled"
  title-logout-started: "&aLogout Started"
  chat-logout-canceled: "&4&lLogger &8» &4Logout Canceled"
  chat-logout-started: "&4&lLogger &8» &aLogout started."
  not-in-this-world: "&4&lLogger &8» &7Logout command is not available in this world!"
  reloaded: "&4[SVC] &7Plugin successfully reloaded."